#!/usr/bin/env node
'use strict';

/*
 * Generates tr/index.html and ar/index.html from index.html.
 *
 * index.html is the English site AND the translation source: it is
 * hand-edited and never generated. Run this after any edit to it.
 *
 * A key marked in the HTML but absent from a language file is a build
 * failure, so a half-translated page cannot be published.
 */

var fs = require('node:fs');
var path = require('node:path');
var transform = require('./i18n-transform.js');

var ROOT = path.join(__dirname, '..');
var BANNER = '<!-- GENERATED by tools/build-i18n.js — edit index.html instead -->';

function loadDictionary(lang) {
  var file = path.join(ROOT, 'i18n', lang + '.json');
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function build() {
  var source = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  var failed = false;

  transform.LANGS.filter(function (lang) { return lang !== 'en'; })
    .forEach(function (lang) {
      var dict = loadDictionary(lang);
      var report = transform.validateKeys(source, dict);

      if (report.missing.length) {
        failed = true;
        console.error('[' + lang + '] missing ' + report.missing.length + ' key(s):');
        report.missing.forEach(function (key) { console.error('  - ' + key); });
      }
      if (report.orphaned.length) {
        console.warn('[' + lang + '] unused key(s) in i18n/' + lang + '.json:');
        report.orphaned.forEach(function (key) { console.warn('  - ' + key); });
      }
      if (report.missing.length) return;

      var result = transform.substitute(source, dict);

      // A marker the substitution could not reach — a void element, a nested
      // same-named tag, an attribute holding '>' — would otherwise ship as
      // English with the build still reporting success. Compare occurrences,
      // not distinct keys: a key used twice, reachable once, must still fail.
      var expected = transform.countMarkers(source);
      if (result.count !== expected) {
        failed = true;
        console.error('[' + lang + '] substituted ' + result.count + ' of ' +
          expected + ' markers — ' + (expected - result.count) +
          ' could not be reached. Check the element shape (void elements and ' +
          'nested same-name tags cannot be substituted).');
        var never = transform.collectKeys(source);
        never.text.concat(never.attr).forEach(function (key) {
          if (result.replaced.indexOf(key) === -1) console.error('  - ' + key);
        });
        return;
      }

      var html = result.html;
      html = transform.localizeJsonLd(html, dict);
      html = transform.rewriteHead(html, lang);
      html = transform.absolutizeAssets(html);
      html = BANNER + '\n' + html;

      var outDir = path.join(ROOT, lang);
      fs.mkdirSync(outDir, { recursive: true });
      fs.writeFileSync(path.join(outDir, 'index.html'), html, 'utf8');
      console.log('wrote ' + lang + '/index.html');
    });

  if (failed) {
    console.error('\nBuild failed: fill the missing keys before publishing.');
    process.exit(1);
  }
}

build();
